#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace ExampleProject
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ExampleProject.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ExampleProject.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<ExampleProject.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ExampleProject.be_Faggruppe"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ExampleProject.be_Faggruppe> be_FaggruppeSet
		{
			get
			{
				return this.CreateQuery<ExampleProject.be_Faggruppe>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="ExampleProject.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<ExampleProject.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<ExampleProject.Contact>();
			}
		}
	}
}
#pragma warning restore CS1591
