#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace UC_EarlyBounds
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class OrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public OrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="UC_EarlyBounds.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<UC_EarlyBounds.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<UC_EarlyBounds.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="UC_EarlyBounds.be_Faggruppe"/> entities.
		/// </summary>
		public System.Linq.IQueryable<UC_EarlyBounds.be_Faggruppe> be_FaggruppeSet
		{
			get
			{
				return this.CreateQuery<UC_EarlyBounds.be_Faggruppe>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="UC_EarlyBounds.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<UC_EarlyBounds.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<UC_EarlyBounds.Contact>();
			}
		}
	}
}
#pragma warning restore CS1591
